#!/usr/bin/env python3

import pygmy

from IPython.terminal.embed import embed
from pygmy.core.initialize import initialize
from pygmy.config import config
from pygmy.app.link import shorten, unshorten, link_stats
from pygmy.model import *

initialize()

banner = """
        ************************************
       * Pygmy: Open Source Link Shortner *
      ************************************
      """
db = config.db.store
pygmy_context = dict(pygmy=pygmy, config=config,
                     Link=Link, LinkManager=LinkManager,
                     User=User, UserManager=UserManager,
                     shorten=shorten, unshorten=unshorten,
                     link_stats=link_stats, db=db)

embed(banner1=banner, local_ns=pygmy_context)
